### ISSUE TITLE
Cannot obtain token

### ISSUE THREAD

**Issue by ghost** [matlink/token-dispenser#3]
Hello,

I installed your fork on my FreeBSD and I cannot obtain a token using gsfid. Return is always 403 forbidden. I used to put my gmail login and password in password file and the return doesn't look as a correct token.

`6wXokoHFQHvI5o2ZoqyP06x4LSOEAoy6vdF91mQDGa6n-0YzcKbsKnPZgbOqkEji9t1CPw.`

I am a member of Exodus Privacy and we use your service a lot. To discharge your instance we want to create our own.

Thanks for your help.

**Comment by matlink** [comment]
This is a correct token. However, if you plan to use it with gplaycli, you also need the gsfid, which is also returned for the path `/email/gsfid`

**Comment by ghost** [comment]
Yes, we use token-dispenser with gplaycli. So did I need to put gsfid in the password file? If yes, which password did I need to use?

**Comment by matlink** [comment]
No, tokendispenser fetches a gsfid at the same time than the token. Just make a GET request to http://yourserver:port/email/gsfid
