### ISSUE TITLE
GSFid issue

### ISSUE THREAD

**Issue by mertcelen** [matlink/token-dispenser#6]
Hello there

I started using docker version of the server and it works perfectly fine for retrieving tokens but not gsfid. It says not found when i try to get it.

Any ideas for that?

I'm trying to get it from this adress http://***.com:8080/email/gsfid

**Comment by ramiskalkan** [comment]
I have the same problem. Any update?

**Comment by matlink** [comment]
Looks like you're running the yeriomin version and not mine. Please retry either by building the image from the Dockerfile of this repo or by using matlink/token-dispenser image available from the docker hub.
If you use mine, please paste the commands you ran.

**Comment by mertcelen** [comment]
Resolved, could you please update readme as well.

**Comment by nguyenvulong** [comment]
Solution  that worked for me:
edit this file: **_src/main/resources/config.properties_**
> enable-email-retrieval=false
